name: Download
description: Downloads URLs to a local directory
author: https://github.com/matrix-org
requirements: []
configuration:
  properties:
    urls:
      type: array
    target-directory:
      type: string

  required:
    - urls
