steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files: hooks/**

  - label: ":sparkles:"
    plugins:
      plugin-linter#v2.0.0:
        id: matrix-org/download

  - wait

  - label: try it out
    command: cat $BUILDKITE_DOWNLOADS_PATH/README.md
    plugins:
      - ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          urls:
            - https://raw.githubusercontent.com/matrix-org/download-buildkite-plugin/master/README.md